Implementation task auth
ChiniakinD/auth pull request #1
Opened 2024-08-04 17:37 UTC by ChiniakinD

2024-08-07 09:34 UTC, gobaz095 requested changes
Мало тестов

2024-08-07 09:34 UTC, gobaz095 commented on src/main/java/com/chiniakin/auth/controller/RoleController.java
> +    public void saveRole(@RequestBody RoleModel roleModel, HttpServletRequest request) {
Не вижу проверки на наличие ролей

2024-08-11 20:26 UTC, ChiniakinD commented on src/main/java/com/chiniakin/auth/controller/RoleController.java
> +    public void saveRole(@RequestBody RoleModel roleModel, HttpServletRequest request) {
https://github.com/ChiniakinD/auth/pull/1/commits/838130dd93e5096edc7ceeafb978b088d4424ab1

2024-08-19 18:02 UTC, gobaz095 approved these changes
В целом можно слить

2024-08-20 07:01 UTC, merged